sudo: required

services:
  - docker

env:
  - distribution: centos
    version: 7
  - distribution: ubuntu
    version: xenial

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'
