# File for Travis-CI
sudo: required

services:
  - docker

env:
  - distribution: centos
    version: 7
    mysql: 5.5
  - distribution: centos
    version: 7
    mysql: 5.6
  - distribution: ubuntu
    version: xenial
    mysql: 5.5
  - distribution: ubuntu
    version: xenial
    mysql: 5.6

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

jobs:
  include:
    - stage: build container
      name: "Building the Ansible docker container"
      script: container_id=$(mktemp)
      script: 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-mysql:ro ${distribution}-${version}:ansible > "${container_id}"'
    - stage: linting
      name: "Testing confirmity to BCP."
      script: 'sudo docker exec "$(cat ${container_id})" ansible-lint --force-color /etc/ansible/roles/ansible-mysql/site.yml'
    - stage: testing
      name: "Running Ansible on Containers"
      script: 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-mysql/travis/test.yml --syntax-check -e mysql_version=${mysql} -e test_run=true'
      script: 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v  /etc/ansible/roles/ansible-mysql/travis/test.yml -e mysql_version=${mysql} -e test_run=true'
      script: >
              sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-mysql/travis/test.yml
              | grep -q 'changed=0.*failed=0'
              && (echo 'Idempotence test: pass' && exit 0)
              || (echo 'Idempotence test: fail' && exit 1)
     - stage: cleanup
       name: "Wiping Docker containers"
       script: 'sudo docker rm -f "$(cat ${container_id})"'
