# File for Travis-CI
sudo: required

services:
  - docker

env:
#  - distribution: centos
#    version: 7
#    mysql: 5.5
#  - distribution: centos
#    version: 7
#    mysql: 5.6
  - distribution: ubuntu
    version: xenial
    mysql: 5.5
  - distribution: ubuntu
    version: xenial
    mysql: 5.6

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-mysql:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-mysql/travis/test.yml --syntax-check -e mysql_version=${mysql} -e test_run=true'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v  /etc/ansible/roles/ansible-mysql/travis/test.yml -e mysql_version=${mysql} -e test_run=true'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-mysql/travis/test.yml -e mysql_version=${mysql} -e test_run=true
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: PASS' && exit 0)
    || (echo 'Idempotence test: FAIL' && exit 1)
  - >
    sudo docker exec "$(cat ${container_id})" mysql --version
    | grep -q '${version}'
    && (echo 'MySQL Version Test: PASS' && exit 0)
    || (echo 'MySQL Version Test: FAIL' && exit 1) 
  - 'sudo docker rm -f "$(cat ${container_id})"'
