---

- name: Remove anonymous users for all hosts.
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Set root password.
  mysql_user:
    name: root
    password: "{{ root_password }}"
    priv: '*.*:ALL'
    state: present
    update_password: always
  no_log: true

- name: Drop a my.cnf for root.
  template:
    src: "{{ role_path }}/files/my.cnf.j2"
    dest: /root/.my.cnf
    owner: root
    mode: 0644
  when: ansible_distribution == "CentOS"
