---
- name: Ubuntu specific AppArmor workaround
  systemd:
    name: apparmor
    state: stopped
    enabled: no
  when: (ansible_distribution == "Ubuntu" and test_run is not defined)

- name: Ubuntu specific password workarounds - Set First Time
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password"
    value: "{{ root_password | quote }}"
    vtype: password
  when: ansible_distribution == "Ubuntu"
  changed_when: False

- name: Ubuntu specific password workarounds - Set Second Time
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password_again"
    value: "{{ root_password | quote }}"
    vtype: password
  when: ansible_distribution == "Ubuntu"
  changed_when: False

- name: Install MySQL Server and MySQL Python interface.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_server_package }}"
    - "{{ mysql_python_package }}"

- name: Enable MySQL Server and Ensure Running.
  systemd:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes
  when: system_daemon == "systemd"

