---

- name: Test if Ubuntu Workarounds have already been performed.
  command: grep "{{ root_password }}" /var/cache/debconf/passwords.dat
  changed_when: no
  register: ubuntu_mysql_passwords_set

- name: Ubuntu specific password workarounds - Set First Time
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password"
    value: "{{ root_password | quote }}"
    vtype: password
  when: (ansible_distribution == "Ubuntu" and ubuntu_mysql_passwords_set == False)

- name: Ubuntu specific password workarounds - Set Second Time
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password_again"
    value: "{{ root_password | quote }}"
    vtype: password
  when: (ansible_distribution == "Ubuntu" and ubuntu_mysql_passwords_set == False)

- name: Install MySQL Server and MySQL Python interface.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_server_package }}"
    - "{{ mysql_python_package }}"

- name: Enable MySQL Server and Ensure Running.
  systemd:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes
  when: system_daemon == "systemd"

    
