---

- name: Install MySQL Server and MySQL Python interface.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_server_package }}"
    - "{{ mysql_python_package }}"

- name: Enable MySQL Server and Ensure Running.
  systemd:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes
  when: system_daemon == "systemd"

    
