---

- name: Download MySQL Community Repo
  get_url:
    url: http://repo.mysql.com/{{ mysql_repo_rpm }}
    dest: /tmp

- name: Install MySQL Community Repo
  yum: 
  name: /tmp/{{ mysql_repo_rpm }}
 
