# OS Specific Facts
- name: Set OS Specific facts.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: Install MySQL repository (Ubuntu).
  include: apt/install_repo_deb.yml 
  when:  ansible_distribution  == "Ubuntu"

- name: Install MySQL repository (RedHat / CentOS).
  include: yum/install_repo_yum.yml
  when: ansible_distribution  == "CentOS"

- name: Include Disable Tasks for Centos (MySQL 5.5)
  include: yum/yum_disable_5_5.yml
  when: (mysql_version == "5.6" and ansible_distribution  == "CentOS")

- name: Include Disable Tasks for Ubuntu (MySQL 5.5)
  include: apt/apt_disable_5_5.yml
  when: (mysql_version == "5.6" and ansible_distribution  == "Ubuntu")

- name: Include Disable Tasks for CentOS (MySQL 5.6)
  include: yum/yum_disable_5_6.yml
  when: (mysql_version == "5.5" and ansible_distribution  == "CentOS")

- name: Include Disable Tasks for Ubuntu (MySQL 5.6)
  include: apt/apt_disable_5_6.yml
  when: (mysql_version == "5.5" and ansible_distribution  == "Ubuntu")

- name: Include Disable Tasks for CentOS (MySQL 5.7)
  include: yum/yum_disable_5_7.yml
  when: (mysql_version is defined and ansible_distribution == "CentOS")

- name: Include Disable Tasks for Ubuntu (MySQL 5.7)
  include: apt/apt_disable_5_7.yml
  when: (mysql_version is defined and ansible_distribution == "Ubuntu")

- name: Install MySQL Server
  include: install_mysql_server.yml
  when: mysql_version is defined 
