# OS Specific Facts
- name: Set OS Specific facts
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: this is just a placeholder
  command: /bin/cat "{{ package_manager }}" > /tmp/test
