# OS Specific Facts
- name: Set OS Specific facts
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

# Setup/install tasks for RedHat
#- include_tasks: setup-RedHat.yml
#  when: ansible_os_family == 'RedHat'

# Setup/install tasks for Ubuntu
#- include_tasks: setup-Ubuntu.yml
#  when: ansible_os_family == 'Ubuntu'
