# Setup/install tasks for RedHat
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Setup/install tasks for Ubuntu
- include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Ubuntu'
