---
- name: Set up MySQL {{ mysql_version }} Community repository.
  yum_repository:
  name: mysql56-community
  description: "Community repositories for MySQL"
  mirrorlist: "MIRRORS FOR MYSQL"
  failovermethod: priority
  gpgkey: "GPG_KEY FOR MYSQL"
  gpgcheck: yes
  enabled: yes
  when: mysql_version == 5.6

- name: Set up MySQL {{ mysql_version }} Community repository.
  yum_repository:
  name: mysql57-community
  description: "Community repositories for MySQL"
  mirrorlist: "MIRRORS FOR MYSQL"
  failovermethod: priority
  gpgkey: "GPG_KEY FOR MYSQL"
  gpgcheck: yes
  enabled: yes
  when: mysql_version == 5.7

- name: Ensure dependancies are installed.
  package:
    name:
      - DEPENDANCY

