---

- name: Download MySQL Community Repo
  get_url:
    url: http://repo.mysql.com/{{ mysql_repo_rpm }}
    dest: /tmp

- name: Install MySQL Community Repo
  yum: 
  name: /tmp/{{ mysql_repo_rpm }}

- name: Toggle MySQL version - 5.5
  ini_file:
    dest: "{{ mysql_repo_location }}"
    section: "{{ mysql_5_5_section }}"
    option: enabled
    value: 1
  when: mysql_version == "5.5"
  notify: yum_clean_metadata

- name: Toggle MySQL version - 5.6
  ini_file:
    dest: "{{ mysql_repo_location }}"
    section: "{{ mysql_5_6_section }}"
    option: enabled
    value: 1
  when: mysql_version == "5.6"
  notify: yum_clean_metadata

#- name: Disable Repository Not Being Used (5.7)
#  ini_file:
#    dest: "{{ mysql_repo_location }}"
#    section: "{{ mysql_5_7_section }}"
#    option: enabled
#    value: 0
#  when: disable_repo_5_7

  

 
